#pragma once

constexpr int EPERM = 1; /* Operation not permitted 操作不允许 */;
constexpr int ENOENT = 2; /* No such file or directory 文件/路径不存在 */
constexpr int ESRCH = 3; /* No such process 进程不存在 */
constexpr int EINTR = 4; /* Interrupted system call 中断的系统调用 */
constexpr int EIO = 5; /* I/O error I/O 错误 */
constexpr int ENXIO = 6; /* No such device or address 设备/地址不存在 */
constexpr int E2BIG = 7; /* Arg list too long 参数列表过长 */
constexpr int ENOEXEC = 8; /* Exec format error 执行格式错误 */
constexpr int EBADF = 9; /* Bad file number 错误文件编号 */
constexpr int ECHILD = 10; /* No child processes 子进程不存在 */
constexpr int EAGAIN = 11; /* Try again 重试 */
constexpr int ENOMEM = 12; /* Out of memory 内存不足 */
constexpr int EACCES = 13; /* Permission denied 无权限 */
constexpr int EFAULT = 14; /* Bad address 地址错误 */
constexpr int ENOTBLK = 15; /* Block device required 需要块设备 */
constexpr int EBUSY = 16; /* Device or resource busy 设备或资源忙 */
constexpr int EEXIST = 17; /* File exists 文件已存在 */
constexpr int EXDEV = 18; /* Cross-device link 跨设备链路 */
constexpr int ENODEV = 19; /* No such device 设备不存在 */
constexpr int ENOTDIR = 20; /* Not a directory 路径不存在 */
constexpr int EISDIR = 21; /* Is a directory 是路径 */
constexpr int EINVAL = 22; /* Invalid argument 无效参数 */
constexpr int ENFILE = 23; /* File table overflow 文件表溢出 */
constexpr int EMFILE = 24; /* Too many open files 打开的文件过多 */
constexpr int ENOTTY = 25; /* Not a typewriter 非打字机 */
constexpr int ETXTBSY = 26; /* Text file busy 文本文件忙 */
constexpr int EFBIG = 27; /* File too large 文件太大 */
constexpr int ENOSPC = 28; /* No space left on device 设备无空间 */
constexpr int ESPIPE = 29; /* Illegal seek 非法查询 */
constexpr int EROFS = 30; /* Read-only file system 只读文件系统 */
constexpr int EMLINK = 31; /* Too many links 链接太多 */
constexpr int EPIPE = 32; /* Broken pipe 管道破裂 */
constexpr int EDOM = 33; /* Math argument out of domain of func 参数超出函数域 */
constexpr int ERANGE = 34; /* Math result not representable 结果无法表示 */
constexpr int EDEADLK = 35; /* Resource deadlock would occur 资源将发生死锁 */
constexpr int ENAMETOOLONG = 36; /* File name too long 文件名太长 */
constexpr int ENOLCK = 37; /* No record locks available 没有可用的记录锁 */
constexpr int ENOSYS = 38; /* Function not implemented 函数未实现 */
constexpr int ENOTEMPTY = 39; /* Directory not empty 目录非空 */
constexpr int ELOOP = 40; /* Too many symbolic links encountered 遇到太多符号链接 */
constexpr int EWOULDBLOCK = EAGAIN; /* Operation would block 操作会阻塞 */
constexpr int ENOMSG = 42; /* No message of desired type 没有符合需求类型的消息 */
constexpr int EIDRM = 43; /* Identifier removed 标识符已删除 */
constexpr int ECHRNG = 44; /* Channel number out of range 通道编号超出范围 */
constexpr int EL2NSYNC = 45; /* Level 2 not synchronized level2不同步 */
constexpr int EL3HLT = 46; /* Level 3 halted 3级停止 */
constexpr int EL3RST = 47; /* Level 3 reset 3级重置 */
constexpr int ELNRNG = 48; /* Link number out of range 链接编号超出范围 */
constexpr int EUNATCH = 49; /* Protocol driver not attached 协议驱动程序没有连接 */
constexpr int ENOCSI = 50; /* No CSI structure available 没有可用的CSI结构 */
constexpr int EL2HLT = 51; /* Level 2 halted 2级停止 */
constexpr int EBADE = 52; /* Invalid exchange 无效交换 */
constexpr int EBADR = 53; /* Invalid request descriptor 无效请求描述 */
constexpr int EXFULL = 54; /* Exchange full 交换完全 */
constexpr int ENOANO = 55; /* No anode 无阳极 */
constexpr int EBADRQC = 56; /* Invalid request code 无效请求码 */
constexpr int EBADSLT = 57; /* Invalid slot 无效插槽 */
constexpr int EDEADLOCK = EDEADLK;
constexpr int EBFONT = 59; /* Bad font file format 错误的字体文件格式 */
constexpr int ENOSTR = 60; /* Device not a stream 设备不是流 */
constexpr int ENODATA = 61; /* No data available 无数据 */
constexpr int ETIME = 62; /* Timer expired 计时器到期 */
constexpr int ENOSR = 63; /* Out of streams resources 流资源不足 */
constexpr int ENONET = 64; /* Machine is not on the network 机器不在网络上 */
constexpr int ENOPKG = 65; /* Package not installed 包未安装 */
constexpr int EREMOTE = 66; /* Object is remote 对象是远程 */
constexpr int ENOLINK = 67; /* Link has been severed 链接正在服务中 */
constexpr int EADV = 68; /* Advertise error 广告错误 */
constexpr int ESRMNT = 69; /* Srmount error ？*/
constexpr int ECOMM = 70; /* Communication error on send 发送过程中通讯错误 */
constexpr int EPROTO = 71; /* Protocol error 协议错误 */
constexpr int EMULTIHOP = 72; /* Multihop attempted 多跳尝试 */
constexpr int EDOTDOT = 73; /* RFS specific error RFS特定错误 */
constexpr int EBADMSG = 74; /* Not a data message 不是数据类型消息 */
constexpr int EOVERFLOW = 75; /* Value too large for defined data type 对指定的数据类型来说值太大 */
constexpr int ENOTUNIQ = 76; /* Name not unique on network 网络上名字不唯一 */
constexpr int EBADFD = 77; /* File descriptor in bad state 文件描述符状态错误 */
constexpr int EREMCHG = 78; /* Remote address changed 远程地址改变 */
constexpr int ELIBACC = 79; /* Can not access a needed shared library 无法访问需要的共享库 */
constexpr int ELIBBAD = 80; /* Accessing a corrupted shared library 访问损坏的共享库 */
constexpr int ELIBSCN = 81; /* .lib section in a.out corrupted 库部分在a.out损坏 */
constexpr int ELIBMAX = 82; /* Attempting to link in too many shared libraries 试图链接太多的共享库 */
constexpr int ELIBEXEC = 83; /* Cannot exec a shared library directly 不能直接运行共享库 */
constexpr int EILSEQ = 84; /* Illegal byte sequence 非法字节序 */
constexpr int ERESTART = 85; /* Interrupted system call should be restarted 应重新启动被中断的系统调用 */
constexpr int ESTRPIPE = 86; /* Streams pipe error 流管错误 */
constexpr int EUSERS = 87; /* Too many users 用户太多 */
constexpr int ENOTSOCK = 88; /* Socket operation on non-socket 在非套接字上进行套接字操作 */
constexpr int EDESTADDRREQ = 89; /* Destination address required 需要目的地址 */
constexpr int EMSGSIZE = 90; /* Message too long 消息太长 */
constexpr int EPROTOTYPE = 91; /* Protocol wrong type for socket 错误协议类型 */
constexpr int ENOPROTOOPT = 92; /* Protocol not available 协议不可用 */
constexpr int EPROTONOSUPPORT = 93; /* Protocol not supported 不支持协议 */
constexpr int ESOCKTNOSUPPORT = 94; /* Socket type not supported 不支持套接字类型 */
constexpr int EOPNOTSUPP = 95; /* Operation not supported on transport endpoint 操作上不支持传输端点 */
constexpr int EPFNOSUPPORT = 96; /* Protocol family not supported 不支持协议族 */
constexpr int EAFNOSUPPORT = 97; /* Address family not supported by protocol 协议不支持地址群 */
constexpr int EADDRINUSE = 98; /* Address already in use 地址已被使用 */
constexpr int EADDRNOTAVAIL = 99; /* Cannot assign requested address 无法分配请求的地址 */
constexpr int ENETDOWN = 100; /* Network is down 网络已关闭 */
constexpr int ENETUNREACH = 101; /* Network is unreachable 网络不可达 */
constexpr int ENETRESET = 102; /* Network dropped connection because of reset 网络由于复位断开连接 */
constexpr int ECONNABORTED = 103; /* Software caused connection abort 软件导致连接终止 */
constexpr int ECONNRESET = 104; /* Connection reset by peer 连接被对方复位 */
constexpr int ENOBUFS = 105; /* No buffer space available 没有可用的缓存空间 */
constexpr int EISCONN = 106; /* Transport endpoint is already connected 传输端点已连接 */
constexpr int ENOTCONN = 107; /* Transport endpoint is not connected 传输端点未连接 */
constexpr int ESHUTDOWN = 108; /* Cannot send after transport endpoint shutdown 传输端点关闭后不能在发送 */
constexpr int ETOOMANYREFS = 109; /* Too many references: cannot splice 太多的引用：无法接合 */
constexpr int ETIMEDOUT = 110; /* Connection timed out 连接超时 */
constexpr int ECONNREFUSED = 111; /* Connection refused 连接被拒绝 */
constexpr int EHOSTDOWN = 112; /* Host is down 主机已关闭 */
constexpr int EHOSTUNREACH = 113; /* No route to host 无法路由到主机 */
constexpr int EALREADY = 114; /* Operation already in progress 操作已在进程中 */
constexpr int EINPROGRESS = 115; /* Operation now in progress 进程中正在进行的操作 */
constexpr int ESTALE = 116; /* Stale NFS file handle  */
constexpr int EUCLEAN = 117; /* Structure needs cleaning  */
constexpr int ENOTNAM = 118; /* Not a XENIX named type file  */
constexpr int ENAVAIL = 119; /* No XENIX semaphores available  */
constexpr int EISNAM = 120; /* Is a named type file  */
constexpr int EREMOTEIO = 121; /* Remote I/O error  */
constexpr int EDQUOT = 122; /* Quota exceeded  */
constexpr int ENOMEDIUM = 123; /* No medium found  */
constexpr int EMEDIUMTYPE = 124; /* Wrong medium type  */
